### ISSUE TITLE
'Unexpected Error' on setting Navcycle

### ISSUE THREAD

**Issue by pmller** [JetStream96/QSimPlanner#3] opened 2016-08-20 08:49 UTC
Uppon selecting current the Navigraph Navcycle the application quits on me with an 'unexpected error'. I originally had this issue with an older Navcycle, but it does persist with the current one. Also: The Navcycle is highlighted in red, even though it is current. 

![qsim-issue](https://cloud.githubusercontent.com/assets/5089011/17830157/ac2aee00-66c3-11e6-8401-7a60a50015a0.gif)

Of course the error might well be on my part, though I think everything should be fine. I tested the cycle in the Aerosoft Airbus and it works fine there, so the Navcycle itself should be ok.

**Comment by JetStream96** [comment] 2016-08-20 09:26
Looks like you are using an older version. The problem is cause by different decimal marks used by different systems. Some countries use .(dot) as decimal mark but others use ,(comma). This should be already fixed in the latest version (0.2.2).

I will fix the red AIRAC text. Thanks for reporting that.

**Comment by pmller** [comment] 2016-08-20 09:53
Thanks for your reply: Indeed I did manage to download 0.2.0 instead of 0.2.2 and I can now confirm that the issue is fixed for me and the application starts just fine.

**Closed** 2016-08-20 16:16 UTC
